### ISSUE TITLE
Cursor should change to pointer when hovering over Import dropdown icon

### ISSUE THREAD

**Issue by udiboy1209** [mozilla/wptview#101]
The two triangles are text, technically. So when I hover over them, my mouse becomes a text cursor which is default behavior. It should become a pointer (hand symbol).

The fix is pretty easy, just adding `cursor: pointer` somewhere in the css/html

**Comment by martiansideofthemoon** [comment]
@udiboy1209 , yeah easy fix, could you do it?

**Comment by martiansideofthemoon** [comment]
@udiboy1209 , could you put the commit in a new PR?
