### ISSUE TITLE
Bug in Clear All because `run_id` is null when deleting comments

### ISSUE THREAD

**Issue by udiboy1209** [mozilla/wptview#108]
I guess I missed this case when implementing #99. When `run_id` is null/undefined, as is the case with clear all, `deleteEntries` gives an error at [this line](https://github.com/mozilla/wptview/blob/master/LovefieldService.js#L495). All that is needed is a check for this [query declaration](https://github.com/mozilla/wptview/blob/master/LovefieldService.js#L492) on `run_id`. Something like [this](https://github.com/mozilla/wptview/blob/master/LovefieldService.js#L522).

I might fix this if I get time, but till then opening an issue.

**Comment by martiansideofthemoon** [comment]
Yeah encountered this bug today. Will try to fix it soon
