### ISSUE TITLE
Page scrolls to the top on pressing result status, can't see a comment box sometimes

### ISSUE THREAD

**Issue by martiansideofthemoon** [mozilla/wptview#109]
@udiboy1209 , have you encountered the same? might need some css fix up

**Comment by udiboy1209** [comment]
I have, and I told you guys about this I guess in the comments PR thread. I don't think its because of CSS, but because the result list disappears and reappears, causing browser to scroll to top when loading the status-box. Let me try a small fix I have in mind.

**Comment by udiboy1209** [comment]
I haven't yet encountered the comment box not being shown problem

**Comment by martiansideofthemoon** [comment]
![image](https://cloud.githubusercontent.com/assets/8805240/13775567/3e0e63e4-eacb-11e5-9ee4-c243dc044f61.png)

**Comment by martiansideofthemoon** [comment]
@udiboy1209 ^^

**Comment by udiboy1209** [comment]
Ohh this, I think it is because the Message is too long, its pushing the comment box out of the screen. Restricting the left section length will do the job.

**Comment by martiansideofthemoon** [comment]
Good job!
