### ISSUE TITLE
Can't see the bottom set of Buttons / Results while the error panel is open

### ISSUE THREAD

**Issue by martiansideofthemoon** [mozilla/wptview#115]
We want something like this :- [https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound&selectedJob=24462486](https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound&selectedJob=24462486)

Scroll to the bottom of this page.. Try collapsing the panel after this.
@udiboy1209 , would you like to work on this?

**Comment by udiboy1209** [comment]
This should be a basic HTML fix, i think. I'll take it up :smiley:

**Comment by martiansideofthemoon** [comment]
@udiboy1209 Thanks! :smile:
