### ISSUE TITLE
Display the error message, if any

### ISSUE THREAD

**Issue by martiansideofthemoon** [mozilla/wptview#13]
The table has no support for displaying the error message for tests that fail. We need some UI to display messages for such tests. The UI decided is a panel fixed to the bottom that opens on clicking the status and closes on clicking anywhere else. The error message is stored here [1]. It can be accessed via `$scope.results.runs[<some_index>].message`. Something similar to `status` in [2]

[1] - https://github.com/jgraham/wptview/blob/dcc68d8ffffafc7eca8b080becd825fab5a5d61d/angular_scripts.js#L309
[2] - https://github.com/jgraham/wptview/blob/dcc68d8ffffafc7eca8b080becd825fab5a5d61d/index.html#L132

**Comment by martiansideofthemoon** [comment]
@CodeMaxx , do you want to do this? I need to get done with #50 as soon as possible, so no time for this. As this isn't so urgent, you can take your time :smile:

**Comment by CodeMaxx** [comment]
@martiansideofthemoon I'll do this

**Comment by martiansideofthemoon** [comment]
I'll update the description by night time. Assigning it to you. Do you need my half complete patch?

**Comment by CodeMaxx** [comment]
@martiansideofthemoon I would like to take a look at it though I'll start my patch from scratch.

**Comment by martiansideofthemoon** [comment]
@CodeMaxx I've updated the description, do tell me if you need more info

**Comment by martiansideofthemoon** [comment]
@CodeMaxx , did you get a chance to dig into the code?

**Comment by CodeMaxx** [comment]
Not yet. Will do by Monday.

**Comment by martiansideofthemoon** [comment]
@CodeMaxx , alright !

**Comment by CodeMaxx** [comment]
@martiansideofthemoon  can you please send your half-complete patch

**Comment by martiansideofthemoon** [comment]
@CodeMaxx , I'm really sorry, I think I've misplaced the patch. So I'll walk you through this patch.
The patch has essentially three steps involved.
Part 1 :- Create a sort of panel which is fixed to the bottom of the screen. It's primary role is to display the message (if any) for a given test result. This panel should open on pressing any of the results under "Actual". So this may involve adding an onclick listener to them. The message has been stored in a variable as mentioned in comment 1.
Part 2 :- Make this panel close on pressing anywhere else.
Part 3 :- Style it to perfection. This is not the goal here, and might need inputs from @jgraham. So focus on part 1 and 2. Let me know if you have any queries. :smile: Thanks for your interest!

**Comment by CodeMaxx** [comment]
@martiansideofthemoon I'll require some pointers as to how to structure the code.

**Comment by martiansideofthemoon** [comment]
@CodeMaxx any progress ? I can explain the parts of the code you fail to understand. :smile:

**Comment by jgraham** [comment]
This is currently the biggest missing piece of functionality for wptview.

@CodeMaxx Are you going to work on this? It might make sense to take a different issue if you want something smaller to start with.
