### ISSUE TITLE
Add a loading dialog while logs are ingested

### ISSUE THREAD

**Issue by martiansideofthemoon** [mozilla/wptview#14]
Logs do take some time to make their way into the database. In the meantime, the user shouldn't be allowed to interact. (For now, we could queue log files in the future). A loading dialog of some form seems an option here. The button being talked about is [1] and [2]. This spinner should rotate until `busy` goes to `false`.

[1] - https://github.com/jgraham/wptview/blob/442ae4ff68c61a03c16789d629968ad8b6a8c2fd/index.html#L47
[2] - https://github.com/jgraham/wptview/blob/442ae4ff68c61a03c16789d629968ad8b6a8c2fd/index.html#L116

**Comment by jgraham** [comment]
FWIW I think we should find a little spinner action and after one clicks any button that sets `busy = true` display the spinner next to that button so it's clear what's going on.

**Comment by sumith1896** [comment]
Are the line numbers pointing correctly? I think some new commits made them point to wrong lines.
Press `y` and clicking on a line number to add the commit hash to the url, this preserves it for future usage.

**Comment by martiansideofthemoon** [comment]
@Sumith1896, yeah we have had a lot of changes in wptview. Thanks for the tip, I've followed it and updated the description. Do tell me if you are interested in this issue.

**Comment by martiansideofthemoon** [comment]
Thanks @udiboy1209 ! Remove the "urgent" tag for now. This is better than the original approach in my opinion. Let's see what @jgraham has to say about this.

**Comment by jgraham** [comment]
I think the spinner is good.
