### ISSUE TITLE
Enable the "Enforce HTTPS" option for github pages

### ISSUE THREAD

**Issue by edmorley** [mozilla/wptview#144]
Please can you force HTTPS, using the option mentioned here:
https://help.github.com/articles/securing-your-github-pages-site-with-https/

...to help avoid mixed content issues (eg in bug 1295382) and since we should be using HTTPS if we can anyway.

**Comment by martiansideofthemoon** [comment]
@edmorley I personally cannot access the settings in the repository, I'm not sure if @jgraham can. Could you add me to the mozilla org / ask someone from the mozilla org to do it?

**Comment by edmorley** [comment]
It needs a repo admin to do so, which I am not.

**Comment by martiansideofthemoon** [comment]
@AutomatedTester can you help us?

**Comment by AutomatedTester** [comment]
done

**Comment by edmorley** [comment]
Thanks :-)
