### ISSUE TITLE
Add an ALL option to the runs column

### ISSUE THREAD

**Issue by martiansideofthemoon** [mozilla/wptview#21]
So the current filtering structure allows us to build queries like "Gecko has STATUS = PASS or OK or SKIP". If we want to get all results which show ERROR for all runs (Servo and Gecko let's say), then we will need to add two constraints, the first saying "Gecko is ERROR" and the second saying "Servo is ERROR". It would be convinient if we could add an "ALL" option (implying both Gecko and Servo are ERROR).
One nuance that is important here is that we need to disable the "Results from <run name>" option if ALL is selected. ("ALL" is not "Results from Gecko" makes no sense). One must disable this option when only one run is present (you have imported only one log file)

**Comment by sumith1896** [comment]
Could you elaborate? I would like to fix this.

**Comment by martiansideofthemoon** [comment]
@Sumith1896 , I've updated the issue description. If you would like to work on it, I'll go about describing a brief procedure to solve it along with some code hints.

**Comment by martiansideofthemoon** [comment]
@jgraham , @Sumith1896 I'll start working on this bug :smile:
