### ISSUE TITLE
Setup a lint for this project

### ISSUE THREAD

**Issue by martiansideofthemoon** [mozilla/wptview#22]
A lint needs to be setup to ensure detection of errors like trailing spaces, space on either side of operators, indentation misses, and other **nits**.

**Comment by sumith1896** [comment]
By `lint`, you mean Python scripts will do or are there some standard Moz way of doing this?

I could give a Python script.

**Comment by martiansideofthemoon** [comment]
python scripts will do :smile:

**Comment by sumith1896** [comment]
Could you list the exact set of lints you need to get this closed?

**Comment by martiansideofthemoon** [comment]
So trailing spaces, correct "two spaces" indentation, space on either side of operators, use of `===` instead of `==`, space after comma are some of the nits that need to be addressed by the lint file.

**Comment by udiboy1209** [comment]
These seem like good linters for JS/CSS: http://eslint.org/ and https://github.com/fidian/PrettyCSS

@jgraham what do other moz projects generally use?

**Comment by martiansideofthemoon** [comment]
@udiboy1209 , we want `eslint`, like it's mentioned on the closed PR

**Comment by udiboy1209** [comment]
@martiansideofthemoon missed that comment on the closed PR! I can make a new PR with a travis config if you'd like. Is Travis enabled for this repo?

**Comment by sumith1896** [comment]
@udiboy1209 Work is open here https://github.com/mozilla/wptview/pull/116

**Comment by udiboy1209** [comment]
Ohh! i've been wasting my time then :stuck_out_tongue_closed_eyes:

**Comment by martiansideofthemoon** [comment]
@Sumith1896 , that PR is irrelevant to the bug now

**Comment by sumith1896** [comment]
I intended to reply to the Travis query. Should have made myself more clear.

**Comment by martiansideofthemoon** [comment]
@udiboy1209 , #116 tries to achieve automatic push to `gh-pages`. You can add the lint to travis in a separate PR once it's complete

**Comment by martiansideofthemoon** [comment]
@udiboy1209 , Travis CI has now been completed, you could rebase and work on this

**Comment by martiansideofthemoon** [comment]
thanks @udiboy1209  :smile:
