### ISSUE TITLE
Next button causes some problem

### ISSUE THREAD

**Issue by martiansideofthemoon** [mozilla/wptview#40]
In the last page of pagination, pressing NEXT makes the interface unusable. We could probably disable the button here. The same error is also observed when no results are found. `test_id` cannot be null is the error.

**Comment by martiansideofthemoon** [comment]
@CodeMaxx, this was a really simple fix, try to see how it was done. Should have given you more time but it was sort of urgent and I thought you got busy as you didn't leave a comment here.

**Comment by CodeMaxx** [comment]
@martiansideofthemoon Yeah adding an `if` did the job. I had just started it today so no pains.

**Comment by martiansideofthemoon** [comment]
@CodeMaxx , yeah but the `else` is also really important here (Else we get stuck in an endless loop).  We can further optimize the code by moving the check to LovefieldService, (saves one query) but it isn't really necessary. If you come up with a patch (a bit less trivial, you need to understand promises), I'll reopen this bug and merge your patch. Also, do mention on the issue tracker if you start working on this or some other patch. Thanks :smile:
