### ISSUE TITLE
Clean up issue

### ISSUE THREAD

**Issue by martiansideofthemoon** [mozilla/wptview#41]
So we need to do 2 things here.
1. _Tidy up filter variables to a neat nested object_ - So as one can see in [1], we have three objects being passed around, namely `$scope.filter`, `$scope.pathFilter` and `$scope.testTypeFilter`. If we could wrap it up in a JSON like,

``` (javascript)
{
   "statusFilter": $scope.filter,
   "pathFilter": $scope.pathFilter,
   "testTypeFilter": $scope.testTypeFilter
}
```

So we pass this composite object rather than three parameters. Corresponding changes need to be made in the functions defined in [2] and [3].
2. _Replace `==` with `===`_. We will prefer strict equality here.

[1] - https://github.com/jgraham/wptview/blob/master/angular_scripts.js#L219
[2] - https://github.com/jgraham/wptview/blob/master/angular_scripts.js#L107
[3] - https://github.com/jgraham/wptview/blob/master/LovefieldService.js#L288

**Comment by CodeMaxx** [comment]
@martiansideofthemoon I would like to work on this issue

**Comment by martiansideofthemoon** [comment]
Hi @CodeMaxx, I hope the description suffices. Do let me or @jgraham know if you need some more information. Assigning it to you. File a PR when you are done.

**Comment by CodeMaxx** [comment]
Thanxx. I'm on it.

**Comment by CodeMaxx** [comment]
Recommended name for the json object?

**Comment by martiansideofthemoon** [comment]
`filter` would do. Give a shot at it, I'll tell you more at the PR

**Comment by CodeMaxx** [comment]
cool

**Comment by martiansideofthemoon** [comment]
Thank you @CodeMaxx :smile:
