### ISSUE TITLE
Import Log takes forever on Firefox

### ISSUE THREAD

**Issue by sumith1896** [mozilla/wptview#50]
Works on Chromium though. 
Reported to @martiansideofthemoon 

![bug](https://cloud.githubusercontent.com/assets/9217608/12075779/1dadcdd0-b1b2-11e5-88dc-c45f2d886a1b.png)

**Comment by martiansideofthemoon** [comment]
So this seems to be more of an issue with `SimpleHTTPServer` rather than repository itself. Thank you for reporting it, I'll need to make changes to `README.md`. The repository works on Firefox when added to `/var/www/html/`.

**Comment by martiansideofthemoon** [comment]
So closing this for now, as #53 describes the problem better. I'll talk to @jgraham once about the best way to host it on localhost. Thanks for your contributions :smile:

**Comment by martiansideofthemoon** [comment]
Reopening this issue, as there is some problem with the repository. Will try to figure out why as soon as I get the time.

**Comment by martiansideofthemoon** [comment]
So I've discovered a few things here.
1. The issue only happens on Firefox / Nightly
2. The code never proceeds beyond [this](https://github.com/jgraham/wptview/blob/e2cbfa654b95a5ce5a01ff83ea1aa9d2a0bf90fb/logcruncher.js#L37) line during the "read" command.
3. The issue has crept in after [this](https://github.com/jgraham/wptview/commit/46774f539ef65219cce128e86db36ecd442b9ff4) commit which adds web worker APIs, solving many earlier issues.

Here are two links that seem to address the problem. The [first](http://stackoverflow.com/questions/22741478/firefox-filereader-is-not-defined-only-when-called-from-web-worker#22851550) is probably why this is happening. The [second](https://bugzilla.mozilla.org/show_bug.cgi?id=901097) is a Bugzilla link about the same.

I think @jgraham would be the best person here.

**Comment by martiansideofthemoon** [comment]
So I spoke to a few people and it seems Firefox doesn't support `FileReader` in web workers yet. It has been fixed and will be around in April's update. So we need to move away from `FileReader` and use `FileReaderSync` instead.
