### ISSUE TITLE
Move to a Node.js server

### ISSUE THREAD

**Issue by cruck12** [mozilla/wptview#53]
Lightweight Node server would be perfect for hosting the service.
Would address compatibility issues plus get it ready for production.

**Comment by martiansideofthemoon** [comment]
@cruck12 , thanks for the idea. I'll talk to @jgraham about the best hosting mechanism for this repository and get back on this issue. For now, I'll edit [README.md](https://github.com/jgraham/wptview/blob/master/README.md) with a browser specification.

**Comment by martiansideofthemoon** [comment]
So we have decided going against a node server, as it isn't really needed for a set a few static files. As the project expands and the need arises, we will repoen this issue. Thanks anyway, @cruck12 :smile:
