### ISSUE TITLE
Adding Travis Continuous Integration

### ISSUE THREAD

**Issue by sumith1896** [mozilla/wptview#56]
On the long run, CI is needed. Travis can be setup but I am not sure if it is needed now.
I feel if we have code_quality lints, it is good to setup and run the script once on Travis.
Anyways, I need your views @jgraham @martiansideofthemoon

**Comment by martiansideofthemoon** [comment]
I think this is the next step, now that wptview is growing.

**Comment by martiansideofthemoon** [comment]
fixed in a series of commits following the PR
