### ISSUE TITLE
Add an option to edit run names after import

### ISSUE THREAD

**Issue by martiansideofthemoon** [mozilla/wptview#61]

**Comment by arpan98** [comment]
I'm interested in this. Do you mean the name in the table? I'm still not through with the code so could you give me some place to start?

**Comment by martiansideofthemoon** [comment]
@arpan98, sure you can work on this :smile: This one is probably a bit tougher than the other issue you have submitted a patch for. So yes, I mean the "Run Name" in the table. Maybe we could add a small edit icon out there. Remember, this issue will need you to run a query modifying the run name. So to start, you could look at [1] to get an idea about where the HTML lies. [2] gives you an idea about how to write a query. ([2] is run from the call at [3]). Happy coding :smile: 

[1] - https://github.com/jgraham/wptview/blob/12ad5e0b0e7d7f09958fab590e7b1e474283eec8/index.html#L25
[2] - https://github.com/jgraham/wptview/blob/12ad5e0b0e7d7f09958fab590e7b1e474283eec8/LovefieldService.js#L91
[3] - https://github.com/jgraham/wptview/blob/12ad5e0b0e7d7f09958fab590e7b1e474283eec8/angular_scripts.js#L69

**Comment by arpan98** [comment]
@martiansideofthemoon What names should be disallowed? And what should happen if the user enters an invalid name? Is it possible to have two runs with different log files but same run names?

Also, what does the [selectParticularRun](https://github.com/jgraham/wptview/blob/12ad5e0b0e7d7f09958fab590e7b1e474283eec8/LovefieldService.js#L499) function do? What options do I have to get the run_id of a run from the table?

**Comment by martiansideofthemoon** [comment]
@arpan98 finally :smile: Really good work, it wasn't so easy after all as the labels say.
