### ISSUE TITLE
Ability to add annotations and notes against a test (especially FAIL) for further processing

### ISSUE THREAD

**Issue by martiansideofthemoon** [mozilla/wptview#62]
Since wptview is useful for comparing structured logs, it would be a good idea to add an annotation system of some sort, which would be downloadable in the "Save" option for further usage. This would typically be added in the error panel.

**Comment by martiansideofthemoon** [comment]
@udiboy1209 , would you like to work on this? It's applicable now since we merged the error panel last night. Now you can open an error panel by clicking on the "Expected" result of a job.

**Comment by udiboy1209** [comment]
@martiansideofthemoon yes this sounds interesting :smile:! I'll work on this.

By annotations do you want something like popups we see in pdfs etc. or just a section in the error panel. If its the latter, "Comments" might be a more approriate title. And what data should the annotation/comment hold?

**Comment by martiansideofthemoon** [comment]
@udiboy1209 , I meant comments, text comments

**Comment by martiansideofthemoon** [comment]
@udiboy1209 Thanks! :smile: you have done some great work for this project!
