### ISSUE TITLE
Blank options under <select> should be taken care of

### ISSUE THREAD

**Issue by martiansideofthemoon** [mozilla/wptview#69]
We have a number of <select> fields that have a blank option selected by default. It would be a good idea to remove all such blank options as it could lead to unforseen errors.

**Comment by Manishearth** [comment]
:+1:

**Comment by udiboy1209** [comment]
+1

**Comment by goutham7r** [comment]
Gulab Jamun bache hain kya?

**Comment by sumith1896** [comment]
I'm working on this.

**Comment by khandelwalbharat** [comment]
nice

**Comment by martiansideofthemoon** [comment]
Thanks @Sumith1896 :smile: and thanks @goutham7r for the background commentary :smile:
