### ISSUE TITLE
Show some form of a progress bar while logs load

### ISSUE THREAD

**Issue by martiansideofthemoon** [mozilla/wptview#80]
We could show a progress bar or the step on which the ingestion process is in. Log ingestion takes up to a minute.

**Comment by arpan98** [comment]
I'm interested to work on this! Could you give me some pointers on where to start and some idea about the flow of control?

**Comment by martiansideofthemoon** [comment]
@arpan98 , yeah sure :smile: This feature is not so well defined, so let's do it step by step. @jgraham will  have more to say about this. I think we can start off by adding steps for log ingestion. Log ingestion primarily needs the following steps :- 
1. Download the file (if URL mode)
2. Read the file
3. Add tests
4. Add test results
5. Add subtests
6. Add subtest results

If you observe the console at any point of time, you will see these steps being logged. [This](https://github.com/jgraham/wptview/blob/master/angular_scripts.js#L65) aptly shows the sequence of promises. We need to add a UI component for this. Would you be interested? If not, maybe you could see the other active issues in wptview. :smile: Feel free to explore!

**Comment by arpan98** [comment]
@martiansideofthemoon Check out the fix [https://github.com/jgraham/wptview/pull/85](url)
