### ISSUE TITLE
Prevent two logs from having the same run name

### ISSUE THREAD

**Issue by martiansideofthemoon** [mozilla/wptview#81]
If we import two logs with the same run name and file, we get a Lovefield error. We should disallow ingestion with the same run name.

**Comment by robodhruv** [comment]
@martiansideofthemoon I'm interested and will be working on it...

**Comment by martiansideofthemoon** [comment]
Yeah sure, you could work on this issue.
[This](https://github.com/jgraham/wptview/blob/12ad5e0b0e7d7f09958fab590e7b1e474283eec8/index.html#L51) is the input field that the filtering has to be carried out on. [This](https://github.com/jgraham/wptview/blob/12ad5e0b0e7d7f09958fab590e7b1e474283eec8/angular_scripts.js#L128) JS object has details on which runs are currently loaded. Do let me know if you need more information. The goal is to disable the "Import" button if the run name is one that is already present. Also, have you been able to run the code?

**Comment by robodhruv** [comment]
@martiansideofthemoon  yes I have it up and running.. I'll get back to you soon! :+1:

**Comment by martiansideofthemoon** [comment]
Great :smile:

**Comment by arpan98** [comment]
I want to work on this issue too! I'll look through the files you have linked above.

**Comment by robodhruv** [comment]
@martiansideofthemoon  Here's the issue resolved. have a look

**Comment by martiansideofthemoon** [comment]
Thanks @nihal111 ! :smile:
