### ISSUE TITLE
Import Log Button should be disabled when Upload File selected but no file uploaded.

### ISSUE THREAD

**Issue by arpan98** [mozilla/wptview#88]
One more condition needs to be added to the disabled condition of the Import Log button to disallow clicking without any file uploaded.

**Comment by udiboy1209** [comment]
A cleaner fix would be to show no file selected when there's no file uploaded, i.e. clear the file input field. That will automatically disable the button and won't leave the user wondering why he can't upload. what do you think @jgraham @martiansideofthemoon ?

**Comment by martiansideofthemoon** [comment]
@udiboy1209 , yeah good idea! Would you like to work on it? Though I'd be happy if someone completes @arpan98 's patch. I want him to have the due credit :smile:

**Comment by udiboy1209** [comment]
@arpan98 's previous PR is not required with the fix I suggest.

I guess only one line needs to be added [here](https://github.com/mozilla/wptview/blob/master/angular_scripts.js#L291) :

```
$scope.logfile.val(null)
```

I would do it but I am a bit busy. @arpan98 you should make a new PR with this, its quite a small fix.

**Comment by malayaleecoder** [comment]
I would like to take this up :)

**Comment by martiansideofthemoon** [comment]
@malayaleecoder , yeah sure! Do tell me if something is unclear. I think @udiboy1209 will be a good mentor here

**Comment by malayaleecoder** [comment]
@martiansideofthemoon : I would need another week to look into this :( In the meantime if anyone else would like to give this a try, please do so :)

**Comment by nihal111** [comment]
I've attempted a fix. Have a look @martiansideofthemoon

**Comment by martiansideofthemoon** [comment]
Thanks @nihal111 :smile:
