### ISSUE TITLE
Consider consuming the w3c-test runner data format

### ISSUE THREAD

**Issue by Ms2ger** [mozilla/wptview#97]
http://w3c-test.org/tools/runner/index.html produces some kind of json. It might be nice to be able to consume it.

**Comment by martiansideofthemoon** [comment]
Yeah sounds like a good idea @Ms2ger :smile: What do you think @jgraham ?

**Comment by jgraham** [comment]
I think it's such a good idea I suggested it and implemented it ;) #98 if you want to review. I need to get reviewable working again I think.

**Comment by martiansideofthemoon** [comment]
@jgraham that was really quick! Would reviewable take sometime? I would prefer that when I review it

**Comment by jgraham** [comment]
https://reviewable.io/reviews/mozilla/wptview/98#-
